version: '3.8'
services:
  pma:
    image: phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
      - PMA_HOST=bdd
  bdd:
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - ./src/main/resources/META-INF/.env